[package]
name = "game_of_life"
version = "0.0.1"
authors = ["modderme123 <modderme123gmail.com>"]
edition = "2018"

[profile.dev.package."*"]
opt-level = 3

[dependencies]
rand = "0.7.3"
wgpu = "0.4"
winit = "0.20.0"
