[package]
name = "rust_test"
version = "0.0.0"
authors = ["Lonsdaleiter <lonsdaleiteproductions@gmail.com>"]
edition = "2018"

[profile.dev.package."*"]
opt-level = 3

[dependencies]
rand = "0.5.5"
wgpu = "0.4"
winit = "0.20.0"
png = "0.15.3"
